services:
  nginx:
    build:
      context: .
      dockerfile: nginx/local/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./logs/nginx:/var/log/nginx
    networks:
      - internal
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php/local/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./logs/php:/var/log/php
    expose:
      - "9000"
    networks:
      - internal
    environment:
      SERVERNAME: db
      DB_ROOT_PASSWORD: strong_password
      DB_NAME: example_db

  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
